### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by wuwei22** [google/tsunami-security-scanner#102]
After I installed it according to the documentation, I started the example and reported an error null pointer.
The error message is as follows:
An exception was caught and reported. Message: java.lang.NullPointerException
java.lang.NullPointerException
	at com.google.tsunami.main.cli.TsunamiCli$TsunamiCliModule.extractPluginServerArgs(TsunamiCli.java:181)
	at com.google.tsunami.main.cli.TsunamiCli$TsunamiCliModule.configure(TsunamiCli.java:161)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:347)
	at com.google.inject.spi.Elements.getElements(Elements.java:104)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:105)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at com.google.inject.Guice.createInjector(Guice.java:59)
	at com.google.tsunami.main.cli.TsunamiCli.main(TsunamiCli.java:258)

6月 05, 2023 12:39:29 下午 com.google.tsunami.main.cli.TsunamiCli main
Critical: Exiting due to workflow execution exceptions.
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) An exception was caught and reported. Message: null
  at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:554)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:161)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:108)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at com.google.inject.Guice.createInjector(Guice.java:59)
	at com.google.tsunami.main.cli.TsunamiCli.main(TsunamiCli.java:258)
Caused by: java.lang.NullPointerException
	at com.google.tsunami.main.cli.TsunamiCli$TsunamiCliModule.extractPluginServerArgs(TsunamiCli.java:181)
	at com.google.tsunami.main.cli.TsunamiCli$TsunamiCliModule.configure(TsunamiCli.java:161)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:347)
	at com.google.inject.spi.Elements.getElements(Elements.java:104)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:105)

======================================================================================
I went to check the source code of the error and found that I couldn't seem to get the plugin.
Line 181 of the TsunamiCli class:
 ((Map) tsunamiConfig.getRawConfigData().get("plugin")).get("callbackserver");

**Comment by am-avios** [comment]
I also got the same exception when running in docker. Can someone assist?

Here is the error in full.

docker run --network="host" -v "$(pwd)/logs":/usr/tsunami/logs tsunami
Jun 12, 2023 9:57:25 PM com.google.tsunami.common.config.YamlConfigLoader configFileReader
WARNING: Unable to read config file 'tsunami.yaml', default to empty config.
Jun 12, 2023 9:57:26 PM com.google.tsunami.main.cli.TsunamiCli main
INFO: Full classpath scan took 1.900 s
Jun 12, 2023 9:57:26 PM com.google.inject.internal.MessageProcessor visit
INFO: An exception was caught and reported. Message: java.lang.NullPointerException
java.lang.NullPointerException
        at com.google.tsunami.main.cli.TsunamiCli$TsunamiCliModule.extractPluginServerArgs(TsunamiCli.java:181)
        at com.google.tsunami.main.cli.TsunamiCli$TsunamiCliModule.configure(TsunamiCli.java:161)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:347)
        at com.google.inject.spi.Elements.getElements(Elements.java:104)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:105)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at com.google.inject.Guice.createInjector(Guice.java:69)
        at com.google.inject.Guice.createInjector(Guice.java:59)
        at com.google.tsunami.main.cli.TsunamiCli.main(TsunamiCli.java:258)

Jun 12, 2023 9:57:26 PM com.google.tsunami.main.cli.TsunamiCli main
SEVERE: Exiting due to workflow execution exceptions.
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) An exception was caught and reported. Message: null
  at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:554)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:161)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:108)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at com.google.inject.Guice.createInjector(Guice.java:69)
        at com.google.inject.Guice.createInjector(Guice.java:59)
        at com.google.tsunami.main.cli.TsunamiCli.main(TsunamiCli.java:258)
Caused by: java.lang.NullPointerException
        at com.google.tsunami.main.cli.TsunamiCli$TsunamiCliModule.extractPluginServerArgs(TsunamiCli.java:181)
        at com.google.tsunami.main.cli.TsunamiCli$TsunamiCliModule.configure(TsunamiCli.java:161)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:347)
        at com.google.inject.spi.Elements.getElements(Elements.java:104)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:105)
        ... 4 more

**Comment by maoning** [comment]
Hi @darlingaoji,

This error has been fixed, could you try pull the latest the changes or switch to use v0.0.17 release and retry?
