### ISSUE TITLE
Run after SUCCESSFUL BUILD 

### ISSUE THREAD

**Issue by chrom** [google/tsunami-security-scanner#12]
Run docker container: 
`...
BUILD SUCCESSFUL in 56s
14 actionable tasks: 14 executed`

Run Scaning:
`java -cp "tsunami-main-0.0.2-SNAPSHOT-cli.jar:/Users/user/tsunami/plugins/*" \
  -Dtsunami-config.location=/Users/user/tsunami/tsunami.yaml \
  com.google.tsunami.main.cli.TsunamiCli \
  --ip-v4-target=127.0.0.1 \
  --scan-results-local-output-format=JSON \
  --scan-results-local-output-filename=/tmp/tsunami-output.json`

`Jun 30, 2020 11:21:57 PM com.google.tsunami.main.cli.TsunamiCli main
INFO: Full classpath scan took 1.207 s
Jun 30, 2020 11:21:57 PM com.google.tsunami.common.config.ConfigModule configure
INFO: Found Tsunami config class: com.google.tsunami.plugins.detectors.credentials.ncrack.NcrackWeakCredentialDetectorConfigs
Jun 30, 2020 11:21:57 PM com.google.tsunami.common.config.ConfigModule configure
INFO: Found Tsunami config class: com.google.tsunami.plugins.portscan.nmap.NmapPortScannerConfigs
Jun 30, 2020 11:21:57 PM com.google.tsunami.common.cli.CliOptionsModule configure
INFO: Found CliOption: com.google.tsunami.common.io.archiving.GoogleCloudStorageArchiver$Options
Jun 30, 2020 11:21:57 PM com.google.tsunami.common.cli.CliOptionsModule configure
INFO: Found CliOption: com.google.tsunami.main.cli.ScanResultsArchiver$Options
Jun 30, 2020 11:21:57 PM com.google.tsunami.common.cli.CliOptionsModule configure
INFO: Found CliOption: com.google.tsunami.main.cli.option.ScanTargetCliOptions
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/Users/user/tsunami/tsunami-main-0.0.2-SNAPSHOT-cli.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Jun 30, 2020 11:21:57 PM com.google.tsunami.plugin.PluginLoadingModule configure
INFO: Found plugin class: com.google.tsunami.plugins.detectors.credentials.ncrack.NcrackWeakCredentialDetector
Jun 30, 2020 11:21:57 PM com.google.tsunami.plugin.PluginBootstrapModule registerPlugin
INFO: Plugin class com.google.tsunami.plugins.detectors.credentials.ncrack.NcrackWeakCredentialDetector is registered.
Jun 30, 2020 11:21:57 PM com.google.tsunami.plugin.PluginLoadingModule configure
INFO: Found plugin class: com.google.tsunami.plugins.detectors.exposedui.hadoop.yarn.YarnExposedManagerApiDetector
Jun 30, 2020 11:21:57 PM com.google.tsunami.plugin.PluginBootstrapModule registerPlugin
INFO: Plugin class com.google.tsunami.plugins.detectors.exposedui.hadoop.yarn.YarnExposedManagerApiDetector is registered.
Jun 30, 2020 11:21:57 PM com.google.tsunami.plugin.PluginLoadingModule configure
INFO: Found plugin class: com.google.tsunami.plugins.detectors.exposedui.jenkins.JenkinsExposedUiDetector
Jun 30, 2020 11:21:57 PM com.google.tsunami.plugin.PluginBootstrapModule registerPlugin
INFO: Plugin class com.google.tsunami.plugins.detectors.exposedui.jenkins.JenkinsExposedUiDetector is registered.
Jun 30, 2020 11:21:57 PM com.google.tsunami.plugin.PluginLoadingModule configure
INFO: Found plugin class: com.google.tsunami.plugins.detectors.exposedui.jupyter.JupyterExposedUiDetector
Jun 30, 2020 11:21:57 PM com.google.tsunami.plugin.PluginBootstrapModule registerPlugin
INFO: Plugin class com.google.tsunami.plugins.detectors.exposedui.jupyter.JupyterExposedUiDetector is registered.
Jun 30, 2020 11:21:57 PM com.google.tsunami.plugin.PluginLoadingModule configure
INFO: Found plugin class: com.google.tsunami.plugins.detectors.exposedui.wordpress.WordPressInstallPageDetector
Jun 30, 2020 11:21:57 PM com.google.tsunami.plugin.PluginBootstrapModule registerPlugin
INFO: Plugin class com.google.tsunami.plugins.detectors.exposedui.wordpress.WordPressInstallPageDetector is registered.
Jun 30, 2020 11:21:57 PM com.google.tsunami.plugin.PluginLoadingModule configure
INFO: Found plugin class: com.google.tsunami.plugins.portscan.nmap.NmapPortScanner
Jun 30, 2020 11:21:57 PM com.google.tsunami.plugin.PluginBootstrapModule registerPlugin
INFO: Plugin class com.google.tsunami.plugins.portscan.nmap.NmapPortScanner is registered.
Jun 30, 2020 11:21:57 PM com.google.tsunami.main.cli.TsunamiCli run
INFO: TsunamiCli starting...
Jun 30, 2020 11:21:57 PM com.google.tsunami.workflow.DefaultScanningWorkflow runAsync
INFO: Staring Tsunami scanning workflow.
Jun 30, 2020 11:21:57 PM com.google.tsunami.main.cli.TsunamiCli main
SEVERE: Exiting due to workflow execution exceptions.
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, java.io.FileNotFoundException: Unable to find a valid nmap binary. Make sure Tsunami config contains a valid nmap binary path.
  at com.google.tsunami.plugins.portscan.nmap.NmapPortScannerBootstrapModule.provideNmapBinaryPath(NmapPortScannerBootstrapModule.java:40) (via modules: com.google.tsunami.main.cli.TsunamiCli$TsunamiCliModule -> com.google.tsunami.plugin.PluginLoadingModule -> com.google.tsunami.plugins.portscan.nmap.NmapPortScannerBootstrapModule)
  while locating java.lang.String annotated with @com.google.tsunami.plugins.portscan.nmap.client.NmapBinaryPath()
    for the 1st parameter of com.google.tsunami.plugins.portscan.nmap.client.NmapClient.<init>(NmapClient.java:211)
  while locating com.google.tsunami.plugins.portscan.nmap.client.NmapClient
    for the 1st parameter of com.google.tsunami.plugins.portscan.nmap.NmapPortScanner.<init>(NmapPortScanner.java:81)
  while locating com.google.tsunami.plugins.portscan.nmap.NmapPortScanner
  while locating com.google.tsunami.plugin.TsunamiPlugin annotated with @com.google.inject.internal.Element(setName=,uniqueId=12, type=MAPBINDER, keyType=com.google.tsunami.plugin.PluginDefinition)

1 error
	at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1097)
	at com.google.tsunami.plugin.PluginManager.lambda$getPortScanners$1(PluginManager.java:53)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.google.tsunami.plugin.PluginManager.getPortScanners(PluginManager.java:55)
	at com.google.tsunami.plugin.PluginManager.getPortScanner(PluginManager.java:60)
	at com.google.tsunami.workflow.DefaultScanningWorkflow.scanPorts(DefaultScanningWorkflow.java:155)
	at com.google.tsunami.workflow.DefaultScanningWorkflow.runAsync(DefaultScanningWorkflow.java:133)
	at com.google.tsunami.workflow.DefaultScanningWorkflow.run(DefaultScanningWorkflow.java:118)
	at com.google.tsunami.main.cli.TsunamiCli.run(TsunamiCli.java:71)
	at com.google.tsunami.main.cli.TsunamiCli.main(TsunamiCli.java:137)
Caused by: java.io.FileNotFoundException: Unable to find a valid nmap binary. Make sure Tsunami config contains a valid nmap binary path.
	at com.google.tsunami.plugins.portscan.nmap.NmapPortScannerBootstrapModule.provideNmapBinaryPath(NmapPortScannerBootstrapModule.java:56)
	at com.google.tsunami.plugins.portscan.nmap.NmapPortScannerBootstrapModule$$FastClassByGuice$$86221da.invoke(<generated>)
	at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264)
	at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:173)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1094)
	... 16 more
`

**Comment by chrom** [comment]
Do not pay attention please.
