### ISSUE TITLE
Docker don't work on unraid

### ISSUE THREAD

**Issue by PrzemekSkw** [google/tsunami-security-scanner#126]
Hello, I want to try tsunami scanner on my unraid server. I install from docker template and after succesfull build it don't start. Logs shows me:
```
Oct 04, 2024 10:43:56 AM com.google.tsunami.plugin.PluginLoadingModule configure
INFO: Found plugin class: com.google.tsunami.plugins.detectors.credentials.ncrack.NcrackWeakCredentialDetector
Oct 04, 2024 10:43:56 AM com.google.tsunami.plugin.PluginBootstrapModule registerPlugin
INFO: Plugin class com.google.tsunami.plugins.detectors.credentials.ncrack.NcrackWeakCredentialDetector is registered.
Oct 04, 2024 10:43:56 AM com.google.tsunami.plugin.PluginLoadingModule configure
INFO: Found plugin class: com.google.tsunami.plugins.detectors.exposedui.hadoop.yarn.YarnExposedManagerApiDetector
Oct 04, 2024 10:43:56 AM com.google.tsunami.plugin.PluginBootstrapModule registerPlugin
INFO: Plugin class com.google.tsunami.plugins.detectors.exposedui.hadoop.yarn.YarnExposedManagerApiDetector is registered.
Oct 04, 2024 10:43:56 AM com.google.tsunami.plugin.PluginLoadingModule configure
INFO: Found plugin class: com.google.tsunami.plugins.detectors.exposedui.jenkins.JenkinsExposedUiDetector
Oct 04, 2024 10:43:56 AM com.google.tsunami.plugin.PluginBootstrapModule registerPlugin
INFO: Plugin class com.google.tsunami.plugins.detectors.exposedui.jenkins.JenkinsExposedUiDetector is registered.
Oct 04, 2024 10:43:56 AM com.google.tsunami.plugin.PluginLoadingModule configure
INFO: Found plugin class: com.google.tsunami.plugins.detectors.exposedui.jupyter.JupyterExposedUiDetector
Oct 04, 2024 10:43:56 AM com.google.tsunami.plugin.PluginBootstrapModule registerPlugin
INFO: Plugin class com.google.tsunami.plugins.detectors.exposedui.jupyter.JupyterExposedUiDetector is registered.
Oct 04, 2024 10:43:56 AM com.google.tsunami.plugin.PluginLoadingModule configure
INFO: Found plugin class: com.google.tsunami.plugins.detectors.exposedui.wordpress.WordPressInstallPageDetector
Oct 04, 2024 10:43:56 AM com.google.tsunami.plugin.PluginBootstrapModule registerPlugin
INFO: Plugin class com.google.tsunami.plugins.detectors.exposedui.wordpress.WordPressInstallPageDetector is registered.
Oct 04, 2024 10:43:56 AM com.google.tsunami.plugin.PluginLoadingModule configure
INFO: Found plugin class: com.google.tsunami.plugins.portscan.nmap.NmapPortScanner
Oct 04, 2024 10:43:56 AM com.google.tsunami.plugin.PluginBootstrapModule registerPlugin
INFO: Plugin class com.google.tsunami.plugins.portscan.nmap.NmapPortScanner is registered.
Oct 04, 2024 10:43:56 AM com.google.inject.internal.MessageProcessor visit
INFO: An exception was caught and reported. Message: com.beust.jcommander.ParameterException: One of the following parameters is expected: --ip-v4-target, --ip-v6-target, --hostname-target
com.beust.jcommander.ParameterException: One of the following parameters is expected: --ip-v4-target, --ip-v6-target, --hostname-target
        at com.google.tsunami.main.cli.option.MainCliOptions.validate(MainCliOptions.java:63)
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:405)
        at com.google.tsunami.common.cli.CliOptionsModule.configure(CliOptionsModule.java:71)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:347)
        at com.google.inject.AbstractModule.install(AbstractModule.java:103)
        at com.google.tsunami.main.cli.TsunamiCli$TsunamiCliModule.configure(TsunamiCli.java:135)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:347)
        at com.google.inject.spi.Elements.getElements(Elements.java:104)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:105)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at com.google.inject.Guice.createInjector(Guice.java:69)
        at com.google.inject.Guice.createInjector(Guice.java:59)
        at com.google.tsunami.main.cli.TsunamiCli.main(TsunamiCli.java:159)

Oct 04, 2024 10:43:56 AM com.google.tsunami.main.cli.TsunamiCli main
SEVERE: Exiting due to workflow execution exceptions.
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) An exception was caught and reported. Message: One of the following parameters is expected: --ip-v4-target, --ip-v6-target, --hostname-target
  at com.google.tsunami.main.cli.TsunamiCli$TsunamiCliModule.configure(TsunamiCli.java:135) (via modules: com.google.tsunami.main.cli.TsunamiCli$TsunamiCliModule -> com.google.tsunami.common.cli.CliOptionsModule)

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:554)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:161)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:108)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at com.google.inject.Guice.createInjector(Guice.java:69)
        at com.google.inject.Guice.createInjector(Guice.java:59)
        at com.google.tsunami.main.cli.TsunamiCli.main(TsunamiCli.java:159)
Caused by: com.beust.jcommander.ParameterException: One of the following parameters is expected: --ip-v4-target, --ip-v6-target, --hostname-target
        at com.google.tsunami.main.cli.option.MainCliOptions.validate(MainCliOptions.java:63)
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:405)
        at com.google.tsunami.common.cli.CliOptionsModule.configure(CliOptionsModule.java:71)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:347)
        at com.google.inject.AbstractModule.install(AbstractModule.java:103)
        at com.google.tsunami.main.cli.TsunamiCli$TsunamiCliModule.configure(TsunamiCli.java:135)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:347)
        at com.google.inject.spi.Elements.getElements(Elements.java:104)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:105)
        ... 4 more

    --port-ranges-target
       A list of port ranges to scan on the scanning target. Specify the
       protocol to use by prepending 'T:' (TCP), 'U:' (UDP) or 'S:' (SCTP).
    --root-paths-target
       A list of application root paths to scan on the scanning target.
    --scan-results-gcs-output-file-url
       The GCS file url for the uploaded scanning results.
    --scan-results-gcs-output-format
       The format of the scanning results uploaded to GCS bucket.
       Possible Values: [BIN_PROTO, JSON]
    --scan-results-local-output-filename
       The local output filename of the scanning results.
    --scan-results-local-output-format
       The format of the scanning results saved as local file.
       Possible Values: [BIN_PROTO, JSON]
       ```
       
       Regards.

**Comment by derpderpington** [comment]
Having this same issue

**Comment by tooryx** [comment]
Hi,

Can you provide the full command line used to run Tsunami?

_~tooryx_

**Comment by PrzemekSkw** [comment]
> Hi,
> 
> Can you provide the full command line used to run Tsunami?
> 
> _~tooryx_

Hi, I run with docker template on unraid.

![image](https://github.com/user-attachments/assets/a1fb995e-57ef-4be4-a8de-fea9f9adafe4)

```
docker run
  -d
  --name='Tsunami'
  --net='host'
  --pids-limit 2048
  --privileged=true
  -e TZ="Europe/Warsaw"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="unRAID"
  -e HOST_CONTAINERNAME="Tsunami"
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/nwithan8/unraid_templates/master/images/tsunami-icon.png'
  -v '/mnt/user/appdata/tsunami/logs':'/usr/tsunami/logs':'rw' 'heywoodlh/tsunami:latest'
ce1768760d8f8f860f94e2baaed1307e3174d70acc7566d53035b9a2ca9a3b8d

The command finished successfully!
```

Tsunami is stoped after that succesfull build with that log:
```
Oct 07, 2024 11:55:29 AM com.google.tsunami.main.cli.TsunamiCli main
SEVERE: Exiting due to workflow execution exceptions.
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) An exception was caught and reported. Message: One of the following parameters is expected: --ip-v4-target, --ip-v6-target, --hostname-target
  at com.google.tsunami.main.cli.TsunamiCli$TsunamiCliModule.configure(TsunamiCli.java:135) (via modules: com.google.tsunami.main.cli.TsunamiCli$TsunamiCliModule -> com.google.tsunami.common.cli.CliOptionsModule)

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:554)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:161)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:108)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at com.google.inject.Guice.createInjector(Guice.java:69)
        at com.google.inject.Guice.createInjector(Guice.java:59)
        at com.google.tsunami.main.cli.TsunamiCli.main(TsunamiCli.java:159)
Caused by: com.beust.jcommander.ParameterException: One of the following parameters is expected: --ip-v4-target, --ip-v6-target, --hostname-target
        at com.google.tsunami.main.cli.option.MainCliOptions.validate(MainCliOptions.java:63)
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:405)
        at com.google.tsunami.common.cli.CliOptionsModule.configure(CliOptionsModule.java:71)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:347)
        at com.google.inject.AbstractModule.install(AbstractModule.java:103)
        at com.google.tsunami.main.cli.TsunamiCli$TsunamiCliModule.configure(TsunamiCli.java:135)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:347)
        at com.google.inject.spi.Elements.getElements(Elements.java:104)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:105)
        ... 4 more

    --port-ranges-target
       A list of port ranges to scan on the scanning target. Specify the
       protocol to use by prepending 'T:' (TCP), 'U:' (UDP) or 'S:' (SCTP).
    --root-paths-target
       A list of application root paths to scan on the scanning target.
    --scan-results-gcs-output-file-url
       The GCS file url for the uploaded scanning results.
    --scan-results-gcs-output-format
       The format of the scanning results uploaded to GCS bucket.
       Possible Values: [BIN_PROTO, JSON]
    --scan-results-local-output-filename
       The local output filename of the scanning results.
    --scan-results-local-output-format
       The format of the scanning results saved as local file.
       Possible Values: [BIN_PROTO, JSON]
       ```

**Comment by tooryx** [comment]
Hi @PrzemekSkw,

Tsunami does not have a webui or a daemon-type container. It runs with a given set of target to be immediately scanned. It means that you need to provide them with either `--ip-v4-target` or `--ip-v6-target` when starting the container.

Hope that helps,
_~tooryx_

**Comment by PrzemekSkw** [comment]
> Hi [@PrzemekSkw](https://github.com/PrzemekSkw),
> 
> Tsunami does not have a webui or a daemon-type container. It runs with a given set of target to be immediately scanned. It means that you need to provide them with either `--ip-v4-target` or `--ip-v6-target` when starting the container.
> 
> Hope that helps, _~tooryx_

Thanks but unfortunately I don't know what to do with that in my docker. 
Regards.
