### ISSUE TITLE
No implementation for java.util.Map

### ISSUE THREAD

**Issue by AkashSullia** [google/tsunami-security-scanner#23]
Ran the command from the howto doc as follow:
```bash
java \                                                                                                                                                     1 ↵  akashsullia 
     -cp "tsunami-main-0.0.2-SNAPSHOT-cli.jar:<path-to-plugin>/*" \
     -Dtsunami.config.location=<path-to>/tsunami-security-scanner/tsunami.yaml \
     com.google.tsunami.main.cli.TsunamiCli \
     --ip-v4-target=<some-ip> \
     --scan-results-local-output-format=JSON \
     --scan-results-local-output-filename=results.json
```

 and received the following error:
```
Jul 10, 2020 3:16:24 AM com.google.tsunami.main.cli.TsunamiCli main
INFO: Full classpath scan took 3.007 s
Jul 10, 2020 3:16:25 AM com.google.tsunami.common.cli.CliOptionsModule configure
INFO: Found CliOption: com.google.tsunami.common.io.archiving.GoogleCloudStorageArchiver$Options
Jul 10, 2020 3:16:25 AM com.google.tsunami.common.cli.CliOptionsModule configure
INFO: Found CliOption: com.google.tsunami.main.cli.ScanResultsArchiver$Options
Jul 10, 2020 3:16:25 AM com.google.tsunami.common.cli.CliOptionsModule configure
INFO: Found CliOption: com.google.tsunami.main.cli.option.ScanTargetCliOptions
Jul 10, 2020 3:16:25 AM com.google.tsunami.main.cli.TsunamiCli main
SEVERE: Exiting due to workflow execution exceptions.
com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for java.util.Map<com.google.tsunami.plugin.PluginDefinition, javax.inject.Provider<com.google.tsunami.plugin.TsunamiPlugin>> was bound.
  while locating java.util.Map<com.google.tsunami.plugin.PluginDefinition, javax.inject.Provider<com.google.tsunami.plugin.TsunamiPlugin>>
    for the 1st parameter of com.google.tsunami.plugin.PluginManager.<init>(PluginManager.java:41)
  while locating com.google.tsunami.plugin.PluginManager
    for the 1st parameter of com.google.tsunami.workflow.DefaultScanningWorkflow.<init>(DefaultScanningWorkflow.java:100)
  while locating com.google.tsunami.workflow.DefaultScanningWorkflow
    for the 1st parameter of com.google.tsunami.main.cli.TsunamiCli.<init>(TsunamiCli.java:63)
  while locating com.google.tsunami.main.cli.TsunamiCli

1 error
        at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1120)
        at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1078)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1131)
        at com.google.tsunami.main.cli.TsunamiCli.main(TsunamiCli.java:139)
```
I tried running it with both jdk-8 and jdk-14.

**Comment by magl0** [comment]
In this case, can you check whether your `<path-to-plugin>` uses the tilde expansion (`~`) feature?  If so, please substitute with the full path. Tilde expansion does not apply in quotes.

**Comment by AkashSullia** [comment]
@magl0, Thank you! That worked. I actually had a path related issue with <path-to-config> and changed it to absolute path. The example given in the how to doc seems to suggest that <path-to-plugin> does tilde expansion. I believe that needs to be updated.
