### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by hannob** [google/tsunami-security-scanner#3]
When I try to run the scanner after following the installation with quick_start.sh on an Ubuntu system I get a lot of Java errors and it doesn't seem to work:
```
Jun 18, 2020 7:27:42 PM com.google.tsunami.main.cli.TsunamiCli main
INFO: Full classpath scan took 944.2 ms
Jun 18, 2020 7:27:42 PM com.google.tsunami.common.config.ConfigModule configure
INFO: Found Tsunami config class: com.google.tsunami.plugins.portscan.nmap.NmapPortScannerConfigs
Jun 18, 2020 7:27:42 PM com.google.tsunami.common.cli.CliOptionsModule configure
INFO: Found CliOption: com.google.tsunami.common.io.archiving.GoogleCloudStorageArchiver$Options
Jun 18, 2020 7:27:42 PM com.google.tsunami.common.cli.CliOptionsModule configure
INFO: Found CliOption: com.google.tsunami.main.cli.ScanResultsArchiver$Options
Jun 18, 2020 7:27:42 PM com.google.tsunami.common.cli.CliOptionsModule configure
INFO: Found CliOption: com.google.tsunami.main.cli.option.ScanTargetCliOptions
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/root/tsunami/tsunami-main-0.0.2-SNAPSHOT-cli.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Jun 18, 2020 7:27:42 PM com.google.tsunami.plugin.PluginLoadingModule configure
INFO: Found plugin class: com.google.tsunami.plugins.detectors.credentials.ncrack.NcrackWeakCredentialDetector
Jun 18, 2020 7:27:42 PM com.google.tsunami.plugin.PluginBootstrapModule registerPlugin
INFO: Plugin class com.google.tsunami.plugins.detectors.credentials.ncrack.NcrackWeakCredentialDetector is registered.
Jun 18, 2020 7:27:42 PM com.google.tsunami.plugin.PluginLoadingModule configure
INFO: Found plugin class: com.google.tsunami.plugins.detectors.exposedui.hadoop.yarn.YarnExposedManagerApiDetector
Jun 18, 2020 7:27:42 PM com.google.tsunami.plugin.PluginBootstrapModule registerPlugin
INFO: Plugin class com.google.tsunami.plugins.detectors.exposedui.hadoop.yarn.YarnExposedManagerApiDetector is registered.
Jun 18, 2020 7:27:42 PM com.google.tsunami.plugin.PluginLoadingModule configure
INFO: Found plugin class: com.google.tsunami.plugins.detectors.exposedui.jenkins.JenkinsExposedUiDetector
Jun 18, 2020 7:27:42 PM com.google.tsunami.plugin.PluginBootstrapModule registerPlugin
INFO: Plugin class com.google.tsunami.plugins.detectors.exposedui.jenkins.JenkinsExposedUiDetector is registered.
Jun 18, 2020 7:27:42 PM com.google.tsunami.plugin.PluginLoadingModule configure
INFO: Found plugin class: com.google.tsunami.plugins.detectors.exposedui.jupyter.JupyterExposedUiDetector
Jun 18, 2020 7:27:42 PM com.google.tsunami.plugin.PluginBootstrapModule registerPlugin
INFO: Plugin class com.google.tsunami.plugins.detectors.exposedui.jupyter.JupyterExposedUiDetector is registered.
Jun 18, 2020 7:27:42 PM com.google.tsunami.plugin.PluginLoadingModule configure
INFO: Found plugin class: com.google.tsunami.plugins.detectors.exposedui.wordpress.WordPressInstallPageDetector
Jun 18, 2020 7:27:42 PM com.google.tsunami.plugin.PluginBootstrapModule registerPlugin
INFO: Plugin class com.google.tsunami.plugins.detectors.exposedui.wordpress.WordPressInstallPageDetector is registered.
Jun 18, 2020 7:27:42 PM com.google.tsunami.plugin.PluginLoadingModule configure
INFO: Found plugin class: com.google.tsunami.plugins.portscan.nmap.NmapPortScanner
Jun 18, 2020 7:27:42 PM com.google.tsunami.plugin.PluginBootstrapModule registerPlugin
INFO: Plugin class com.google.tsunami.plugins.portscan.nmap.NmapPortScanner is registered.
Jun 18, 2020 7:27:42 PM com.google.tsunami.main.cli.TsunamiCli main
SEVERE: Exiting due to workflow execution exceptions.
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2357)
	at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:243)
	at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:115)
	at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:717)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:941)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:863)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:300)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:231)
	at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:949)
	at com.google.inject.internal.FactoryProxy.notify(FactoryProxy.java:48)
	at com.google.inject.internal.ProcessedBindingData.runCreationListeners(ProcessedBindingData.java:60)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:135)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:108)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at com.google.inject.Guice.createInjector(Guice.java:59)
	at com.google.tsunami.main.cli.TsunamiCli.main(TsunamiCli.java:135)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 19 more

**Comment by magl0** [comment]
We have a missing runtime dependency in the gradle script. I'll fix this now.
