### ISSUE TITLE
Error: Could not find or load main class com.google.tsunami.main.cli.TsunamiCli

### ISSUE THREAD

**Issue by mphslaats** [google/tsunami-security-scanner#39]
After a successful build of the quick start script, I get the following output:

```bash
Build successful, execute the following command to scan 127.0.0.1:

cd /c/Users/Mark/tsunami && \
java -cp "tsunami-main-0.0.2-SNAPSHOT-cli.jar:/c/Users/Mark/tsunami/plugins/*" \
  -Dtsunami-config.location=/c/Users/Mark/tsunami/tsunami.yaml \
  com.google.tsunami.main.cli.TsunamiCli \
  --ip-v4-target=127.0.0.1 \
  --scan-results-local-output-format=JSON \
  --scan-results-local-output-filename=/tmp/tsunami-output.json
```
However, if I copy paste the command I am getting an error that the main class cannot be found:
```bash
Mark@TheBeast MINGW64 ~/Downloads/tsunami-security-scanner (master)
$ cd /c/Users/Mark/tsunami && \
> java -cp "tsunami-main-0.0.2-SNAPSHOT-cli.jar:/c/Users/Mark/tsunami/plugins/*" \
>   -Dtsunami-config.location=/c/Users/Mark/tsunami/tsunami.yaml \
>   com.google.tsunami.main.cli.TsunamiCli \
>   --ip-v4-target=127.0.0.1 \
>   --scan-results-local-output-format=JSON \
>   --scan-results-local-output-filename=/tmp/tsunami-output.json
Error: Could not find or load main class com.google.tsunami.main.cli.TsunamiCli
```

The content of `~/tsunami` is:
```bash
Mark@TheBeast MINGW64 ~/tsunami
$ ls -lAh
total 16M
drwxr-xr-x 1 Mark 197121   0 Jul 12 18:28 plugins/
drwxr-xr-x 1 Mark 197121   0 Jul 12 18:28 repos/
-rw-r--r-- 1 Mark 197121 132 Jul 12 18:34 tsunami.yaml
-rw-r--r-- 1 Mark 197121 16M Jul 12 18:34 tsunami-main-0.0.2-SNAPSHOT-cli.jar
```

Application versions:
```bash
Mark@TheBeast MINGW64 ~/tsunami
$ nmap --version
Nmap version 7.80 ( https://nmap.org )
Platform: i686-pc-windows-windows
Compiled with: nmap-liblua-5.3.5 openssl-1.0.2s nmap-libssh2-1.8.2 nmap-libz-1.2.11 nmap-libpcre-7.6 Npcap-0.9982 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: iocp poll select

Mark@TheBeast MINGW64 ~/tsunami
$ ncrack --version

Ncrack version 0.7 ( http://ncrack.org )
Modules: SSH, RDP, FTP, Telnet, HTTP(S), Wordpress, POP3(S), IMAP, CVS, SMB, VNC, SIP, Redis, PostgreSQL, MQTT, MySQL, MSSQL, MongoDB, Cassandra, WinRM, OWA, DICOM
```

**Comment by pereshgithub** [comment]
I set the Path=C:\Users\KING\tsunami\profiles\ in environment variables and executed the below command. 
java -Dtsunami-config.location=C:\Users\KING\tsunami\tsunami.yaml -Xmx100m -jar C:\Users\KING\tsunami\tsunami-main-0.0.2-SNAPSHOT-cli.jar TsunamiCli --gcs-archiver-chunk-size-in-bytes=1000 --gcs-archiver-chunk-upload-threshold-in-bytes=1000000 --hostname-target=localhost --ip-v4-target=127.0.0.1 --ip-v6-target=127.0.0.1 --scan-results-gcs-output-file-url=\tmp\tsunami-output-file-url.txt --scan-results-gcs-output-format=JSON  --scan-results-local-output-filename=\tmp\tsunami-output.json --scan-results-local-output-format=JSON

TsunamiCli is able to load, but it is showing the commandline arguments are not setted properly. Please see the below exception:

Jul 16, 2020 4:25:43 PM com.google.tsunami.main.cli.TsunamiCli main
INFO: Full classpath scan took 6.237 s
Jul 16, 2020 4:25:43 PM com.google.tsunami.common.cli.CliOptionsModule configure
INFO: Found CliOption: com.google.tsunami.common.io.archiving.GoogleCloudStorageArchiver$Options
Jul 16, 2020 4:25:43 PM com.google.tsunami.common.cli.CliOptionsModule configure
INFO: Found CliOption: com.google.tsunami.main.cli.ScanResultsArchiver$Options
Jul 16, 2020 4:25:43 PM com.google.tsunami.common.cli.CliOptionsModule configure
INFO: Found CliOption: com.google.tsunami.main.cli.option.ScanTargetCliOptions
Usage: TsunamiCli [options]
  Options:
    --gcs-archiver-chunk-size-in-bytes
       The size of the data chunk when GCS archiver uploads data to Cloud
       Storage.
       Default: 1000
    --gcs-archiver-chunk-upload-threshold-in-bytes
       The default data size threshold in bytes to enable chunk upload to GCS.
       Default: 1000000
    --hostname-target
       The hostname of the scanning target.
    --ip-v4-target
       The IP v4 address of the scanning target.
    --ip-v6-target
       The IP v6 address of the scanning target.
    --scan-results-gcs-output-file-url
       The GCS file url for the uploaded scanning results.
    --scan-results-gcs-output-format
       The format of the scanning results uploaded to GCS bucket.
       Possible Values: [BIN_PROTO, JSON]
    --scan-results-local-output-filename
       The local output filename of the scanning results.
    --scan-results-local-output-format
       The format of the scanning results saved as local file.
       Possible Values: [BIN_PROTO, JSON]

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/C:/Users/KING/tsunami/tsunami-main-0.0.2-SNAPSHOT-cli.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Jul 16, 2020 4:25:43 PM com.google.inject.internal.MessageProcessor visit
INFO: An exception was caught and reported. Message: com.beust.jcommander.ParameterException: Was passed main parameter 'TsunamiCli' but no main parameter was defined
com.beust.jcommander.ParameterException: Was passed main parameter 'TsunamiCli' but no main parameter was defined
        at com.beust.jcommander.JCommander.getMainParameter(JCommander.java:914)
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:759)
        at com.beust.jcommander.JCommander.parse(JCommander.java:282)
        at com.beust.jcommander.JCommander.parse(JCommander.java:265)
        at com.google.tsunami.common.cli.CliOptionsModule.configure(CliOptionsModule.java:70)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:347)
        at com.google.inject.AbstractModule.install(AbstractModule.java:103)
        at com.google.tsunami.main.cli.TsunamiCli$TsunamiCliModule.configure(TsunamiCli.java:113)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:347)
        at com.google.inject.spi.Elements.getElements(Elements.java:104)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:105)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at com.google.inject.Guice.createInjector(Guice.java:69)
        at com.google.inject.Guice.createInjector(Guice.java:59)
        at com.google.tsunami.main.cli.TsunamiCli.main(TsunamiCli.java:137)

Jul 16, 2020 4:25:43 PM com.google.tsunami.main.cli.TsunamiCli main
SEVERE: Exiting due to workflow execution exceptions.
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) An exception was caught and reported. Message: Was passed main parameter 'TsunamiCli' but no main parameter was defined
  at com.google.tsunami.main.cli.TsunamiCli$TsunamiCliModule.configure(TsunamiCli.java:113) (via modules: com.google.tsunami.main.cli.TsunamiCli$TsunamiCliModule -> com.google.tsunami.common.cli.CliOptionsModule)

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:554)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:161)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:108)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at com.google.inject.Guice.createInjector(Guice.java:69)
        at com.google.inject.Guice.createInjector(Guice.java:59)
        at com.google.tsunami.main.cli.TsunamiCli.main(TsunamiCli.java:137)
Caused by: com.beust.jcommander.ParameterException: Was passed main parameter 'TsunamiCli' but no main parameter was defined
        at com.beust.jcommander.JCommander.getMainParameter(JCommander.java:914)
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:759)
        at com.beust.jcommander.JCommander.parse(JCommander.java:282)
        at com.beust.jcommander.JCommander.parse(JCommander.java:265)
        at com.google.tsunami.common.cli.CliOptionsModule.configure(CliOptionsModule.java:70)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:347)
        at com.google.inject.AbstractModule.install(AbstractModule.java:103)
        at com.google.tsunami.main.cli.TsunamiCli$TsunamiCliModule.configure(TsunamiCli.java:113)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:347)
        at com.google.inject.spi.Elements.getElements(Elements.java:104)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:105)
        ... 4 more

Please suggest how to proceed further.

Thanks
Peresh

**Comment by gbiagomba** [comment]
@pereshgithub unless your issue is related to this, i would recommend creating a separate ticket

**Comment by gbiagomba** [comment]
@mphslaats I am having the same problem as you, i need to dig in and see whats wrong

**Comment by HAE** [comment]
I got the same problem. I'm on Cygwin.
nmap and ncrack are the latest versions,
The quick start build was successful with no errors.

When I run the test for the 127.0.0.1 using suggested command, and executing it in the main Tsunami directory which does include the just built tsunami-main-0.0.5-SNAPSHOT-cli.jar jar file.

```
java -cp "tsunami-main-0.0.5-SNAPSHOT-cli.jar:/home/HAE/tsunami/plugins/*" \
  -Dtsunami-config.location=/home/HAE/tsunami/tsunami.yaml \
  com.google.tsunami.main.cli.TsunamiCli \
  --ip-v4-target=127.0.0.1 \
  --scan-results-local-output-format=JSON \
  --scan-results-local-output-filename=/tmp/tsunami-output.json
```


I get the following error:

```
Error: Could not find or load main class com.google.tsunami.main.cli.TsunamiCli
Caused by: java.lang.ClassNotFoundException: com.google.tsunami.main.cli.TsunamiCli

```

**Comment by coinicarus** [comment]
> I got the same problem. I'm on Cygwin.
> nmap and ncrack are the latest versions,
> The quick start build was successful with no errors.
> 
> When I run the test for the 127.0.0.1 using suggested command, and executing it in the main Tsunami directory which does include the just built tsunami-main-0.0.5-SNAPSHOT-cli.jar jar file.
> 
> ```
> java -cp "tsunami-main-0.0.5-SNAPSHOT-cli.jar:/home/HAE/tsunami/plugins/*" \
>   -Dtsunami-config.location=/home/HAE/tsunami/tsunami.yaml \
>   com.google.tsunami.main.cli.TsunamiCli \
>   --ip-v4-target=127.0.0.1 \
>   --scan-results-local-output-format=JSON \
>   --scan-results-local-output-filename=/tmp/tsunami-output.json
> ```
> 
> I get the following error:
> 
> ```
> Error: Could not find or load main class com.google.tsunami.main.cli.TsunamiCli
> Caused by: java.lang.ClassNotFoundException: com.google.tsunami.main.cli.TsunamiCli
> ```

i am also experiencing this issue as well.

**Comment by coinicarus** [comment]
on my end in terminal window i manually navigated to /root/tsunami and ran ls and found my tsunami-main-0.0.5-SNAPSHOT-cli.jar in the directory. then verified my command... it was looking for 0.0.2... changed it and now the world is well here :)
