### ISSUE TITLE
Error in custom provider, java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by Ne0ks** [google/tsunami-security-scanner#83]
While i'm running the command :

cd /root/tsunami && \
cmdand> java -cp "tsunami-main-0.0.4-SNAPSHOT-cli.jar:/root/tsunami/plugins/*" \
cmdand>   -Dtsunami-config.location=/root/tsunami/tsunami.yaml \
cmdand>   com.google.tsunami.main.cli.TsunamiCli \
cmdand>   --ip-v4-target=127.0.0.1 \
cmdand>   --scan-results-local-output-format=JSON \
cmdand>   --scan-results-local-output-filename=/tmp/tsunami-output.json

There is the error : 

GRAVE: Exiting due to workflow execution exceptions.
java.util.concurrent.ExecutionException: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, java.lang.OutOfMemoryError: Java heap space
  at com.google.tsunami.plugins.fingerprinters.web.WebServiceFingerprinterBootstrapModule.provideFingerprintData(WebServiceFingerprinterBootstrapModule.java:47) (via modules: com.google.tsunami.main.cli.TsunamiCli$TsunamiCliModule -> com.google.tsunami.plugin.PluginLoadingModule -> com.google.tsunami.plugins.fingerprinters.web.WebServiceFingerprinterBootstrapModule)
  while locating com.google.common.collect.ImmutableMap<com.google.tsunami.plugins.fingerprinters.web.proto.SoftwareIdentity, com.google.tsunami.plugins.fingerprinters.web.data.FingerprintData>
    for the 1st parameter of com.google.tsunami.plugins.fingerprinters.web.data.FingerprintRegistry.<init>(FingerprintRegistry.java:35)
  while locating com.google.tsunami.plugins.fingerprinters.web.data.FingerprintRegistry
    for the 1st parameter of com.google.tsunami.plugins.fingerprinters.web.WebServiceFingerprinter.<init>(WebServiceFingerprinter.java:79)
  while locating com.google.tsunami.plugins.fingerprinters.web.WebServiceFingerprinter
  while locating com.google.tsunami.plugin.TsunamiPlugin annotated with @com.google.inject.internal.Element(setName=,uniqueId=46, type=MAPBINDER, keyType=com.google.tsunami.plugin.PluginDefinition)

1 error
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:553)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:534)
        at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:88)
        at com.google.tsunami.workflow.DefaultScanningWorkflow.run(DefaultScanningWorkflow.java:118)
        at com.google.tsunami.main.cli.TsunamiCli.run(TsunamiCli.java:76)
        at com.google.tsunami.main.cli.TsunamiCli.main(TsunamiCli.java:162)

At the end i don't have the tsunami-output.json  file  

Regards

**Comment by nikhil6624** [comment]
Hi @Ne0ks , May I start working on this issue?
